import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        error: "#ba1a1a",
        "on-primary-fixed": "#100069",
        "primary-fixed": "#e3dfff",
        "secondary-container": "#39b8fd",
        "canvas-dark": "#0f172a",
        tertiary: "#553300",
        "on-primary-container": "#c1beff",
        "surface-container-low": "#eff4ff",
        "on-tertiary-fixed": "#2a1700",
        primary: "#2a14b4",
        "error-container": "#ffdad6",
        "surface-dim": "#cbdbf5",
        "on-primary-fixed-variant": "#372abf",
        secondary: "#006591",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#89ceff",
        background: "var(--background)",
        foreground: "var(--foreground)",
        "surface-tint": "#5148d7",
        "on-error-container": "#93000a",
        "primary-container": "#4338ca",
        warning: "#f59e0b",
        "on-tertiary-container": "#ffb759",
        "surface-container": "#e5eeff",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        success: "#10b981",
        "surface-container-high": "#dce9ff",
        "surface-variant": "#d3e4fe",
        danger: "#ef4444",
        "inverse-surface": "#213145",
        "outline-variant": "#c7c4d7",
        "tertiary-fixed-dim": "#ffb95f",
        "inverse-on-surface": "#eaf1ff",
        "border-subtle": "#e2e8f0",
        surface: "#f8f9ff",
        "surface-bright": "#f8f9ff",
        "secondary-fixed": "#c9e6ff",
        "tertiary-container": "#744800",
        "inverse-primary": "#c3c0ff",
        outline: "#777586",
        "on-secondary-container": "#004666",
        "on-secondary-fixed": "#001e2f",
        "on-background": "#0b1c30",
        "canvas-light": "#ffffff",
        "accent-indigo": "#4338ca",
        "accent-blue": "#0ea5e9",
        "on-surface-variant": "#464554",
        "tertiary-fixed": "#ffddb8",
        "on-secondary-fixed-variant": "#004c6e",
        "on-surface": "#0b1c30",
        "surface-container-highest": "#d3e4fe",
        "primary-fixed-dim": "#c3c0ff",
        "on-tertiary-fixed-variant": "#653e00",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "gutter-md": "1rem",
        unit: "4px",
        "sidebar-width": "260px",
        "sidebar-collapsed": "64px",
        "container-max": "1440px",
        "margin-page": "2rem"
      },
      fontFamily: {
        sans: ["Manrope", "var(--font-manrope)", "sans-serif"],
        "display-lg": ["Manrope", "var(--font-manrope)", "sans-serif"],
        "display-lg-mobile": ["Manrope", "var(--font-manrope)", "sans-serif"],
        "headline-md": ["Manrope", "var(--font-manrope)", "sans-serif"],
        "headline-sm": ["Manrope", "var(--font-manrope)", "sans-serif"],
        "body-lg": ["Manrope", "var(--font-manrope)", "sans-serif"],
        "body-md": ["Manrope", "var(--font-manrope)", "sans-serif"],
        "body-sm": ["Manrope", "var(--font-manrope)", "sans-serif"],
        "label-md": ["Manrope", "var(--font-manrope)", "sans-serif"],
        "mono-data": ["var(--font-jetbrains-mono)", "monospace"]
      },
      fontSize: {
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["28px", { lineHeight: "34px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "mono-data": ["13px", { lineHeight: "20px", fontWeight: "450" }]
      }
    },
  },
  plugins: [],
};
export default config;
