"use client";

import { useState } from "react";
import { cn } from "@/lib/utils";

export interface GeneratedReport {
  name: string;
  dateRange: string;
  generatedBy: string;
  status: "Ready" | "Draft";
  iconBg: string;
  iconColor: string;
  icon: string;
}

interface RecentReportsTableProps {
  generated: GeneratedReport[];
}

export function RecentReportsTable({ generated }: RecentReportsTableProps) {
  const [searchQuery, setSearchQuery] = useState("");

  const filteredGenerated = generated.filter((rep) =>
    rep.name.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <section className="space-y-4">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div className="flex items-center gap-2">
          <span className="material-symbols-outlined text-primary">history</span>
          <h3 className="font-headline-md text-headline-md text-on-surface font-bold">
            Recent Reports Generated
          </h3>
        </div>
        <div className="relative w-full sm:w-64">
          <input
            type="text"
            placeholder="Search recent reports..."
            className="w-full pl-9 pr-4 py-1.5 bg-surface border border-outline-variant rounded focus:outline-none focus:ring-1 focus:ring-primary text-body-sm"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
          />
          <span className="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-on-surface-variant text-[18px]">
            search
          </span>
        </div>
      </div>

      <div className="bg-surface border border-outline-variant rounded-xl overflow-hidden shadow-sm">
        <div className="overflow-x-auto">
          <table className="w-full text-left font-body-md border-collapse min-w-[700px]">
            <thead>
              <tr className="bg-surface-container-low border-b border-outline-variant">
                <th className="px-6 py-4 font-label-md text-label-md text-on-surface-variant uppercase text-xs">
                  Report Name
                </th>
                <th className="px-6 py-4 font-label-md text-label-md text-on-surface-variant uppercase text-xs">
                  Date Range
                </th>
                <th className="px-6 py-4 font-label-md text-label-md text-on-surface-variant uppercase text-xs">
                  Generated By
                </th>
                <th className="px-6 py-4 font-label-md text-label-md text-on-surface-variant uppercase text-xs">
                  Status
                </th>
                <th className="px-6 py-4 font-label-md text-label-md text-on-surface-variant uppercase text-xs text-right">
                  Actions
                </th>
              </tr>
            </thead>
            <tbody className="divide-y divide-outline-variant bg-surface-container-lowest">
              {filteredGenerated.map((rep, idx) => (
                <tr key={idx} className="hover:bg-surface-container-low transition-colors">
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-3">
                      <div
                        className={cn(
                          "w-8 h-8 rounded flex items-center justify-center",
                          rep.iconBg
                        )}
                      >
                        <span className={cn("material-symbols-outlined text-sm", rep.iconColor)}>
                          {rep.icon}
                        </span>
                      </div>
                      <span className="font-bold text-sm text-on-surface">{rep.name}</span>
                    </div>
                  </td>
                  <td className="px-6 py-4 font-mono-data text-mono-data text-on-surface-variant">
                    {rep.dateRange}
                  </td>
                  <td className="px-6 py-4 text-on-surface-variant">{rep.generatedBy}</td>
                  <td className="px-6 py-4">
                    <span
                      className={cn(
                        "text-[10px] px-2.5 py-0.5 rounded-full font-bold uppercase",
                        rep.status === "Ready"
                          ? "bg-green-100 text-green-700"
                          : "bg-slate-100 text-slate-700"
                      )}
                    >
                      {rep.status}
                    </span>
                  </td>
                  <td className="px-6 py-4 text-right">
                    <div className="flex justify-end gap-2 text-on-surface-variant">
                      <button
                        onClick={() => alert(`Viewing ${rep.name}...`)}
                        className="p-1 hover:bg-surface-container rounded"
                      >
                        <span className="material-symbols-outlined text-sm">visibility</span>
                      </button>
                      <button
                        onClick={() => alert(`Downloading PDF for ${rep.name}...`)}
                        className="p-1 hover:bg-surface-container rounded"
                      >
                        <span className="material-symbols-outlined text-sm">picture_as_pdf</span>
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
              {filteredGenerated.length === 0 && (
                <tr>
                  <td colSpan={5} className="px-6 py-12 text-center text-on-surface-variant">
                    No matching reports found.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </section>
  );
}
